framework:
    messenger:
        transports:
            NumberCreationRequestAPI.NumberService: "%env(NumberCreationRequestAPI_NumberService)%"

        routing:
            'MessageInfo\NumberCreationRequestAPIDataProvider' : NumberCreationRequestAPI.NumberService


