version: '3'

services:
    redis:
        image: redis:5.0.8
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
    rabbitmq:
        image: rabbitmq:3.7.6-management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 15672:15672
            - 5672:5672
